//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.TextEmailNewsletterStandard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.TextEmailNewsletterStandard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string ArticleNumberSeparator {
            get {
                return ResourceManager.GetString("ArticleNumberSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + .
        /// </summary>
        internal static string ArticleStructurePrefix {
            get {
                return ResourceManager.GetString("ArticleStructurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ends.
        /// </summary>
        internal static string Ends {
            get {
                return ResourceManager.GetString("Ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - .
        /// </summary>
        internal static string ListItemPrefix {
            get {
                return ResourceManager.GetString("ListItemPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        internal static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +++ .
        /// </summary>
        internal static string NewsletterStructurePrefix {
            get {
                return ResourceManager.GetString("NewsletterStructurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string SectionNumberSeparator {
            get {
                return ResourceManager.GetString("SectionNumberSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ++ .
        /// </summary>
        internal static string SectionStructurePrefix {
            get {
                return ResourceManager.GetString("SectionStructurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  per cent.
        /// </summary>
        internal static string SubstitutePercent {
            get {
                return ResourceManager.GetString("SubstitutePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2$3$4 pounds (UK).
        /// </summary>
        internal static string SubstitutePounds {
            get {
                return ResourceManager.GetString("SubstitutePounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This newsletter conforms to the accessible Text Email Newsletter.
        /// </summary>
        internal static string TenStandardLine1 {
            get {
                return ResourceManager.GetString("TenStandardLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (TEN) Standard 1.2:.
        /// </summary>
        internal static string TenStandardLine2 {
            get {
                return ResourceManager.GetString("TenStandardLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.headstar.com/ten/tens-1.2.txt.
        /// </summary>
        internal static string TenStandardUrl {
            get {
                return ResourceManager.GetString("TenStandardUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.eastsussex.gov.uk.
        /// </summary>
        internal static string VirtualUrlBase {
            get {
                return ResourceManager.GetString("VirtualUrlBase", resourceCulture);
            }
        }
    }
}
